/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprocjt;

/**
 *
 * @author leven
 */
public class StudentFrame extends javax.swing.JFrame {

    int index;
    Project pro;
    Students stu;
    
    public StudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        clearIdButton = new javax.swing.JButton();
        stuMessageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crsMessageLabel = new javax.swing.JLabel();
        cNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        cNameField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stuMessageLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("Student ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 30);
        jPanel1.add(idField);
        idField.setBounds(120, 20, 110, 30);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(253, 20, 90, 30);

        clearIdButton.setText("Clear ID");
        clearIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearIdButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearIdButton);
        clearIdButton.setBounds(253, 60, 90, 30);
        jPanel1.add(stuMessageLabel);
        stuMessageLabel.setBounds(10, 60, 200, 30);

        jPanel2.setLayout(null);

        jLabel3.setText("Procejt Name:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 30, 120, 30);

        jLabel4.setText("Project Desc");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 190, 110, 30);

        crsMessageLabel.setToolTipText("");
        crsMessageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(crsMessageLabel);
        crsMessageLabel.setBounds(80, 110, 120, 30);

        cNameField.setEditable(false);
        jPanel2.add(cNameField);
        cNameField.setBounds(170, 30, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 330, 180);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Help?");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 110, 50, 30);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(closeButton);
        closeButton.setBounds(240, 430, 110, 30);

        cNameField1.setEditable(false);

        jLabel6.setText("Name");

        emailtf.setEditable(false);

        jLabel9.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cNameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(emailtf))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stuMessageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(stuMessageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        int id = Integer.parseInt(idField.getText());
        pro=stu.getProject();
        
               
        boolean val;
        val = BilkentSYS.checkRedundancy(id);
        int tid;

        AcademicUnits tmp;
        if (val) {
            for (int i = 0; i < BilkentSYS.getStudents().size(); i++) {
                tmp = BilkentSYS.getStudents().get(i);
                tid = tmp.getIdNumber();
                if (tid == id) {
                    index = i;
                }
            }
            stuMessageLabel.setText("Student Exists!");
            
           cNameField1.setText(stu.getFullName());
           emailtf.setText(stu.contact.getEmail());
            cNameField.setText(pro.getTitle());
            jTextArea1.setText(pro.getShortdesc());
         
             if (pro.gethelp()) {
                 crsMessageLabel.setText("Need Help");}
             else { crsMessageLabel.setText("No help needed");}
  
        }  
        else { stuMessageLabel.setText("No Student Record!");}
   
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearIdButtonActionPerformed
        idField.setText("");
    }//GEN-LAST:event_clearIdButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cNameField;
    private javax.swing.JTextField cNameField1;
    private javax.swing.JButton clearIdButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel crsMessageLabel;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel stuMessageLabel;
    private javax.swing.JLabel stuMessageLabel1;
    // End of variables declaration//GEN-END:variables
}
