
package labguide15_q2;

public class VehicleMain extends javax.swing.JFrame {

    /**
     * Creates new form RentingVehicle
     */
    public VehicleMain() {
        initComponents();
        helicopterPanel.setVisible(false);
        carPanel3.setVisible(false);
        shipPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        type_ComB = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        type_Panel = new javax.swing.JPanel();
        helicopterPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        seatNum_TF = new javax.swing.JTextField();
        grossWeight_TF = new javax.swing.JTextField();
        autorotation_CB = new javax.swing.JCheckBox();
        carPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        coeficent_TF3 = new javax.swing.JTextField();
        power_TF3 = new javax.swing.JTextField();
        area_TF3 = new javax.swing.JTextField();
        transmissionType_TF = new javax.swing.JTextField();
        fuelType_TF = new javax.swing.JTextField();
        shipPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tonnage_TF = new javax.swing.JTextField();
        passangerCount_TF = new javax.swing.JTextField();
        length_TF = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        remove_Button = new javax.swing.JButton();
        id__TF = new javax.swing.JTextField();
        brand_TF = new javax.swing.JTextField();
        model_TF = new javax.swing.JTextField();
        year_TF = new javax.swing.JTextField();
        display_Button = new javax.swing.JButton();
        basePrice_TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea_TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Id:");

        jLabel2.setText("Brand:");

        jLabel3.setText("Model:");

        jLabel4.setText("Year:");

        type_ComB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "All", "Car", "Helicopter", "Ship" }));
        type_ComB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_ComBActionPerformed(evt);
            }
        });

        jLabel5.setText("Type:");

        type_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helicopterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Helicopter"));

        jLabel11.setText("Seat number:");

        jLabel12.setText("Autorotation:");

        jLabel13.setText("Gross Weight:");

        javax.swing.GroupLayout helicopterPanelLayout = new javax.swing.GroupLayout(helicopterPanel);
        helicopterPanel.setLayout(helicopterPanelLayout);
        helicopterPanelLayout.setHorizontalGroup(
            helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helicopterPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helicopterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(seatNum_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(helicopterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(autorotation_CB))
                    .addGroup(helicopterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(grossWeight_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        helicopterPanelLayout.setVerticalGroup(
            helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helicopterPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helicopterPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(seatNum_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(autorotation_CB))
                .addGap(18, 18, 18)
                .addGroup(helicopterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helicopterPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(grossWeight_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        type_Panel.add(helicopterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        carPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Car"));

        jLabel24.setText("Transmission Type:");

        jLabel25.setText("Fuel Type:");

        jLabel26.setText("Coeficent(C):");

        jLabel27.setText("Power(P):");

        jLabel28.setText("Area(A):");

        javax.swing.GroupLayout carPanel3Layout = new javax.swing.GroupLayout(carPanel3);
        carPanel3.setLayout(carPanel3Layout);
        carPanel3Layout.setHorizontalGroup(
            carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carPanel3Layout.createSequentialGroup()
                .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(carPanel3Layout.createSequentialGroup()
                        .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(41, 41, 41)
                        .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coeficent_TF3)
                            .addComponent(power_TF3)
                            .addComponent(area_TF3)))
                    .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(carPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(55, 55, 55)
                            .addComponent(fuelType_TF))
                        .addGroup(carPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(14, 14, 14)
                            .addComponent(transmissionType_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
        );
        carPanel3Layout.setVerticalGroup(
            carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(transmissionType_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(fuelType_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel27)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel28))
                    .addGroup(carPanel3Layout.createSequentialGroup()
                        .addComponent(coeficent_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(power_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(area_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        type_Panel.add(carPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 230));

        shipPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ship"));

        jLabel29.setText("Tonnage:");

        jLabel30.setText("Passanger Count:");

        jLabel31.setText("Length:");

        javax.swing.GroupLayout shipPanelLayout = new javax.swing.GroupLayout(shipPanel);
        shipPanel.setLayout(shipPanelLayout);
        shipPanelLayout.setHorizontalGroup(
            shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(length_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(tonnage_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(passangerCount_TF))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        shipPanelLayout.setVerticalGroup(
            shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tonnage_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(passangerCount_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(length_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        type_Panel.add(shipPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        remove_Button.setText(" Remove");
        remove_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_ButtonActionPerformed(evt);
            }
        });

        display_Button.setText("Display");
        display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Base Price:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(16, 16, 16)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brand_TF)
                                    .addComponent(id__TF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basePrice_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(year_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(model_TF)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Add)
                                .addGap(18, 18, 18)
                                .addComponent(remove_Button))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)
                                .addComponent(type_ComB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(type_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(display_Button)
                        .addGap(151, 151, 151))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(type_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(display_Button)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id__TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brand_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(model_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(year_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(basePrice_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(type_ComB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add)
                    .addComponent(remove_Button))
                .addGap(20, 20, 20))
        );

        displayArea_TA.setColumns(20);
        displayArea_TA.setRows(5);
        jScrollPane1.setViewportView(displayArea_TA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void type_ComBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_ComBActionPerformed
        String res = "";
        if (type_ComB.getSelectedIndex() == 0 || type_ComB.getSelectedIndex() == 1) {
            carPanel3.setVisible(false);
            helicopterPanel.setVisible(false);
            shipPanel.setVisible(false);
            res = "Select a Vehicle type to add!!";
        } else if (type_ComB.getSelectedIndex() == 2) {
            carPanel3.setVisible(true);
            helicopterPanel.setVisible(false);
            shipPanel.setVisible(false);
            res = "Car is selected!!";
        } else if (type_ComB.getSelectedIndex() == 3) {
            helicopterPanel.setVisible(true);
            carPanel3.setVisible(false);
            shipPanel.setVisible(false);
            res = "Helicopter is selected!!";

        } else if (type_ComB.getSelectedIndex() == 4) {
            helicopterPanel.setVisible(false);
            carPanel3.setVisible(false);
            shipPanel.setVisible(true);
            res = "Ship is selected!!";
        }

        displayArea_TA.setText(res);
    }//GEN-LAST:event_type_ComBActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        
        String brand, model, transmissionType, fuelType, type;
        double baseprice, coefficient, power, area, grossWeight, tonnage, length;
        int vehicleId,year, seatNum, passanger;
        boolean autorotation;
        Car c;
        Helicopter h;
        Ship s;
        vehicleId = Integer.parseInt(id__TF.getText());
        System.out.println("Vehicle ıd:"+vehicleId);
        brand = brand_TF.getText();
        model = model_TF.getText();
        baseprice = Double.parseDouble(basePrice_TF.getText());
        year = Integer.parseInt(year_TF.getText());
        int vehicleType = type_ComB.getSelectedIndex();
        String typeVehicle = "";
        switch (vehicleType) {
            case 2:
                transmissionType = transmissionType_TF.getText();
                fuelType = fuelType_TF.getText();
                coefficient = Double.parseDouble(coeficent_TF3.getText());
                power = Double.parseDouble(power_TF3.getText());
                area = Double.parseDouble(area_TF3.getText());
                System.out.println("c="+coefficient+"p="+power+"a="+area);
                c = new Car(vehicleId, brand, model, baseprice, year, transmissionType, fuelType, coefficient, power, area);
                
                boolean val=VehicleSys.addVheicle(c);
                System.out.println("Car: "+val+"\n"+ c.toString());
                typeVehicle = "Car";
                break;
            case 3:
                seatNum = Integer.parseInt(seatNum_TF.getText());
                autorotation = autorotation_CB.isSelected();
                grossWeight = Double.parseDouble(grossWeight_TF.getText());
                h = new Helicopter(vehicleId, brand, model, baseprice, year, seatNum, autorotation, grossWeight);
                 val=VehicleSys.addVheicle(h);
                typeVehicle = "Helicopter";
                System.out.println("Helicopter: "+val+"\n"+ h.toString());
                break;
            case 4:
                tonnage = Double.parseDouble(tonnage_TF.getText());
                passanger = Integer.parseInt(passangerCount_TF.getText());
                length = Double.parseDouble(length_TF.getText());
                s = new Ship(vehicleId, brand, model, baseprice, year, tonnage, passanger, year);
                val=VehicleSys.addVheicle(s);
                 System.out.println("Ship: "+val+"\n"+ s.toString());
                typeVehicle = "Ship";
                break;

        }
        displayArea_TA.setText(typeVehicle + "is added to the array list!!");


    }//GEN-LAST:event_AddActionPerformed

    private void remove_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_ButtonActionPerformed
        int id = Integer.parseInt(id__TF.getText());
        VehicleSys.removeVehicle(id);
        displayArea_TA.setText(id + " is deleted from the array list!!");
    }//GEN-LAST:event_remove_ButtonActionPerformed

    private void display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_ButtonActionPerformed
        String vehicleType = (String) type_ComB.getSelectedItem();
        String res = "";
        if (vehicleType.equalsIgnoreCase("All")) {
            res = VehicleSys.getAllVehicle();
        } else if (vehicleType.equalsIgnoreCase("None")) {
            res = "Select a valid vehicle type";
        } else {
            res = VehicleSys.getSelectedVehicle(vehicleType);
        }
        displayArea_TA.setText(""+res);
    }//GEN-LAST:event_display_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField area_TF3;
    private javax.swing.JCheckBox autorotation_CB;
    private javax.swing.JTextField basePrice_TF;
    private javax.swing.JTextField brand_TF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel carPanel3;
    private javax.swing.JTextField coeficent_TF3;
    private javax.swing.JTextArea displayArea_TA;
    private javax.swing.JButton display_Button;
    private javax.swing.JTextField fuelType_TF;
    private javax.swing.JTextField grossWeight_TF;
    private javax.swing.JPanel helicopterPanel;
    private javax.swing.JTextField id__TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField length_TF;
    private javax.swing.JTextField model_TF;
    private javax.swing.JTextField passangerCount_TF;
    private javax.swing.JTextField power_TF3;
    private javax.swing.JButton remove_Button;
    private javax.swing.JTextField seatNum_TF;
    private javax.swing.JPanel shipPanel;
    private javax.swing.JTextField tonnage_TF;
    private javax.swing.JTextField transmissionType_TF;
    private javax.swing.JComboBox<String> type_ComB;
    private javax.swing.JPanel type_Panel;
    private javax.swing.JTextField year_TF;
    // End of variables declaration//GEN-END:variables
}
